inherit_from: .rubocop_todo.yml
plugins:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/ResponseParsedBody:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/Exit:
  Enabled: false