---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/transactions":
    get:
      summary: list transactions
      tags:
      - Transactions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    amount:
                      type: number
                    title:
                      type: string
                    date:
                      type: date
                    transaction_type:
                      type: string
                    category_id:
                      type: integer
                    created_at:
                      type: datetime
                      format: iso8601
                    updated_at:
                      type: datetime
                      format: iso8601
                    user_id:
                      type: integer
    post:
      summary: create transaction
      tags:
      - Transactions
      parameters: []
      responses:
        '201':
          description: transaction created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                category_id:
                  type: integer
                transaction_type:
                  type: string
                title:
                  type: string
              required:
              - amount
              - category_id
              - transaction_type
              - title
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: localhost:3000
