---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/transactions":
    get:
      summary: list transactions
      tags:
      - Transactions
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    amount:
                      type: number
                    title:
                      type: string
                    date:
                      type: string
                      format: date
                    transaction_type:
                      type: string
                    category_id:
                      type: integer
                    created_at:
                      type: string
                      format: datetime
                    updated_at:
                      type: string
                      format: datetime
                    user_id:
                      type: integer
    post:
      summary: create transaction
      tags:
      - Transactions
      parameters: []
      responses:
        '201':
          description: transaction created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                category_id:
                  type: integer
                transaction_type:
                  type: string
                title:
                  type: string
              required:
              - amount
              - category_id
              - transaction_type
              - title
  "/users/sign_in":
    post:
      summary: sign in
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful sign in
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 200
                      message:
                        type: string
                        example: Logged in successfully.
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          email:
                            type: string
                            example: user@example.com
                          password:
                            type: string
                            example: password123
        '401':
          description: invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
              required:
              - email
              - password
  "/users/":
    post:
      summary: sign up
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: successful sign up
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 201
                      message:
                        type: string
                        example: Signed up successfully.
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          email:
                            type: string
                            example: newuser@example.com
                          password:
                            type: string
                            example: password123
        '422':
          description: validation errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Error message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: newuser@example.com
                    password:
                      type: string
                      example: password123
                    password_confirmation:
                      type: string
                      example: password123
              required:
              - email
              - password
              - password_confirmation
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: localhost:3000
tags:
- name: Authentication
  description: User authentication endpoints
- name: Transactions
  description: Transaction management endpoints
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- Bearer: []
